Publishing designing with users at sba blog post
usds/website pull request #324
Opened 2017-05-31 15:32 UTC by sarahsaltiel

2017-06-02 14:56 UTC, jas298 submitted a review, later dismissed

2017-06-02 14:57 UTC, jas298 commented
@sarahsaltiel removed the colon here, too. Otherwise, LGTM.

@nacingov Can you merge plz?

2017-06-02 15:46 UTC, nacingov requested changes
This filename is missing a date.

2017-06-20 15:04 UTC, jas298 commented
@nacingov fixed!

2017-06-21 19:23 UTC, nacingov approved these changes

2017-06-21 19:23 UTC, merged